<?php
require 'config.php';
require_login();

$code = trim($_GET['code'] ?? '');
$result = null;

if ($code !== '') {
    // Check against OTP first
    $stmt = $pdo->prepare("SELECT n.*, u.name AS customer_name FROM notifications n
        JOIN users u ON n.customer_id = u.id
        WHERE (n.otp_code = ? OR n.anti_spoof_token = ?) AND n.customer_id = ?");
    $stmt->execute([$code, $code, $_SESSION['user_id']]);
    $result = $stmt->fetch(PDO::FETCH_ASSOC);
}
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Verify Alert - Trusted Notifications</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<div class="wrapper">
    <div class="top-bar">
        <div>
            <h1>Verify Alert</h1>
            <p class="text-muted">Check if an OTP / alert was really generated by the bank.</p>
        </div>
        <div>
            <span class="tag">Logged in as <?php echo htmlspecialchars($_SESSION['name']); ?></span>
            <a href="dashboard_customer.php" class="btn small secondary">Back</a>
        </div>
    </div>

    <div class="card">
        <?php if ($code === ''): ?>
            <div class="alert info">No code provided. Please go back and enter a code.</div>
        <?php else: ?>
            <?php if ($result): ?>
                <div class="alert success">
                    This alert is <strong>TRUSTED</strong>.<br>
                    Event: <?php echo htmlspecialchars($result['event_type']); ?> |
                    Channel: <?php echo htmlspecialchars($result['channel']); ?> |
                    Time: <?php echo htmlspecialchars($result['created_at']); ?>
                </div>
            <?php else: ?>
                <div class="alert error">
                    We could not find any alert with this OTP/token for your account.
                    Treat it as suspicious and do not share any details.
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
</body>
</html>
